<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Download: Wed, 26 Nov 2025 15:27:26 +0100 -->
<!--Contact: Takseringshjælp ApS [mail@takseringshjaelp.dk] -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="https://www.ppg-processmanager.com/api/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ProcessManagerAPI" targetNamespace="https://www.ppg-processmanager.com/api/">
	<wsdl:types>
		<xsd:schema targetNamespace="https://www.ppg-processmanager.com/api/">
			<xsd:complexType name="workorderCreateRequest">
				<xsd:sequence>
					<xsd:element name="workorder" type="tns:workorder" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="workorder_import" type="tns:workorder_import" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="source" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="workfield" type="xsd:string" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorder">
				<xsd:sequence>
					<xsd:element name="workorder_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="id" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="plate" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="brand" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="brand_uid" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="model" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="modelyear" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="location_name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="breakdown" type="tns:breakdown" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="jobprovider_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="jobprovider_key" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="jobprovider_name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="jobprovider_debtor" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="owner" type="tns:owner" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="client_key" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="color" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="colorcode" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="layers" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="technic" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="vin" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="mileage_incident" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="mileage_inspection" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="mileage_arrival" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="mileage_handoff" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="possession" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="deadline" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="delivery" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="notice" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="files" type="tns:files" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="sparepart" type="tns:sparepart" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="documentation" type="xsd:boolean" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="value" type="tns:value" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="process_key" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="process_type" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="process_name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="timestamp" type="tns:timestamp" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="extension" type="xsd:string" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorderListRequest">
				<xsd:sequence>
					<xsd:element name="process_type" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="plate" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorderListResponse">
				<xsd:sequence>
					<xsd:element name="workorder" type="tns:workorder" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="breakdown">
				<xsd:sequence>
					<xsd:element name="breakdown_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="uniq_id" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="id" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="type_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="type_name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="requisition" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="lines" type="tns:invoice_line" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="summary" type="tns:summary" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="excess" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="appraiser" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="claim_number" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="claim_date" type="xsd:date" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="owner">
				<xsd:sequence>
					<xsd:element name="number" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="company" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="organization_no" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="address_1" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="address_2" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="city" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="zipcode" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone_mute" type="xsd:boolean" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone_alt" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone_mute_alt" type="xsd:boolean" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="email" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorder_import">
				<xsd:sequence>
					<xsd:element name="service" maxOccurs="1" minOccurs="1">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:minLength value="1"/>
								<xsd:maxLength value="10"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="uniq_id" maxOccurs="1" minOccurs="1">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:minLength value="1"/>
								<xsd:maxLength value="36"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoiceListResponse">
				<xsd:sequence>
					<xsd:element name="invoice_id" type="xsd:int" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoice">
				<xsd:sequence>
					<xsd:element name="invoice_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="invoice_type" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="jobprovider_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="jobprovider_debtor" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="location_code" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="location_name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="lines" type="tns:invoice_line" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="uniq_id" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="requisition" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="warranty" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="warranty_note" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="excess" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="type_id" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="type_name" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="type_template" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="workorder" type="tns:workorder" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="principal_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="principal_debtor" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="owner" type="tns:owner" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoice_line">
				<xsd:sequence>
					<xsd:element name="type" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="subfield" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="number" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="group" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="amount" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="price" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="discount" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="unit" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoiceGetRequest">
				<xsd:sequence>
					<xsd:element name="invoice_id" type="xsd:int" maxOccurs="unbounded" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoiceDoneRequest">
				<xsd:sequence>
					<xsd:element name="invoice_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="invoice_no" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="status" maxOccurs="1" minOccurs="0">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="cre"/>
								<xsd:enumeration value="deb"/>
								<xsd:enumeration value="err"/>
								<xsd:enumeration value="acc"/>
								<xsd:enumeration value="rej"/>
								<xsd:enumeration value="ppd"/>
								<xsd:enumeration value="prt"/>
								<xsd:enumeration value="inv"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="accounting" type="xsd:date" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="feedback" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="files">
				<xsd:sequence>
					<xsd:element name="file_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="mimetype" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="data" type="xsd:base64Binary" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="folder" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="workfield" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="sparepart">
				<xsd:sequence>
					<xsd:element name="part_id" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="partnumber" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="amount" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="price" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="listprice" type="xsd:double" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="used" type="xsd:boolean" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="delivery" type="xsd:date" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="oem_partnumber" maxOccurs="1" minOccurs="0">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:maxLength value="20"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="highlight" type="xsd:boolean" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="summary">
				<xsd:sequence>
					<xsd:element name="type" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="text" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="paintmanagerRepairOrdersResponse">
				<xsd:sequence>
					<xsd:element name="RO" type="tns:RO" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="RO">
				<xsd:sequence>
					<xsd:element name="RONumber" type="xsd:string"/>
					<xsd:element name="ROStatus" type="xsd:string"/>
					<xsd:element name="Customer" type="xsd:string"/>
					<xsd:element name="ROPainterNotes" type="xsd:string"/>
					<xsd:element name="LicensePlateNum" type="xsd:string"/>
					<xsd:element name="VIN" type="xsd:string"/>
					<xsd:element name="ModelYear" type="xsd:int"/>
					<xsd:element name="MakeDesc" type="xsd:string"/>
					<xsd:element name="ModelName" type="xsd:string"/>
					<xsd:element name="OEMColorCode" type="xsd:string"/>
					<xsd:element name="Priority" type="xsd:int"/>
					<xsd:element name="Deadline" type="xsd:date"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="empty"/>
			<xsd:complexType name="paintmanagerMixesResponse">
				<xsd:sequence>
					<xsd:element name="Mix" type="tns:Mix" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="Mix">
				<xsd:sequence>
					<xsd:element name="MixRONumber" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="MixedDate" type="xsd:dateTime" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="MixedBy" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="MixedByEmployeeID" type="xsd:int" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="MixCost" type="xsd:double" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="PPGBrandCode" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="Component" type="tns:Component" maxOccurs="unbounded" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="Component">
				<xsd:sequence>
					<xsd:element name="Code" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="Description" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="WeightApplied" type="xsd:double" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="WeightTarget" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="Density" type="xsd:double" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="value">
				<xsd:sequence>
					<xsd:element name="key" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="value" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoiceGetResponse">
				<xsd:sequence>
					<xsd:element name="invoice" type="tns:invoice" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="jobprovider">
				<xsd:sequence>
					<xsd:element name="jobprovider_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="contact" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="email" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="address" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="number" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="debtor" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="jobproviderUpdateRequest">
				<xsd:sequence>
					<xsd:element name="jobprovider_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="debtor" type="xsd:string" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="jobproviderGetRequest">
				<xsd:sequence>
					<xsd:element name="jobprovider_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="jobproviderListResponse">
				<xsd:sequence>
					<xsd:element name="jobprovider" type="tns:jobprovider" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="principal">
				<xsd:sequence>
					<xsd:element name="principal_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="type" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="company" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="debtor" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="organization_no" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="address" type="tns:address" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="phone" type="tns:phone" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="email" type="tns:email" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="principalListRequest">
				<xsd:sequence>
					<xsd:element name="date_edit" type="xsd:date" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="address">
				<xsd:sequence>
					<xsd:element name="address_1" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="address_2" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="zipcode" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="city" type="xsd:string" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="phone">
				<xsd:sequence>
					<xsd:element name="prefix" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="number" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="note" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="email">
				<xsd:sequence>
					<xsd:element name="value" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="note" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="principalGetRequest">
				<xsd:sequence>
					<xsd:element name="principal_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="principalListResponse">
				<xsd:sequence>
					<xsd:element name="principal" type="tns:principal" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="principalUpdateRequest">
				<xsd:sequence>
					<xsd:element name="principal_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="debtor" type="xsd:string" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="invoiceAttachmentRequest">
				<xsd:sequence>
					<xsd:element name="invoice_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="files" type="tns:files" maxOccurs="unbounded" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="brandListResponse">
				<xsd:sequence>
					<xsd:element name="brand" type="tns:brand" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="brand">
				<xsd:sequence>
					<xsd:element name="uid" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorderGetRequest">
				<xsd:sequence>
					<xsd:element name="workorder_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="workorder" type="tns:workorder" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorderActionRequest">
				<xsd:sequence>
					<xsd:element name="workorder_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="action_key" type="xsd:string" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="bookingListRequest">
				<xsd:sequence>
					<xsd:element name="week" type="xsd:date" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="bookingListResponse">
				<xsd:sequence>
					<xsd:element name="booking" type="tns:booking" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="booking">
				<xsd:sequence>
					<xsd:element name="key" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="date" type="xsd:dateTime" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="bookingSetRequest">
				<xsd:sequence>
					<xsd:element name="workorder_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="booking" type="tns:booking" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="timestamp">
				<xsd:sequence>
					<xsd:element name="create" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="entry" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="production" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="done" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="delivered" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="archive" type="xsd:dateTime" maxOccurs="1" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="planningCapacityRequest">
				<xsd:sequence>
					<xsd:element name="track" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
					<xsd:element name="start" type="xsd:date" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="days" maxOccurs="1" minOccurs="1">
						<xsd:simpleType>
							<xsd:restriction base="xsd:int">
								<xsd:minInclusive value="1"/>
								<xsd:maxInclusive value="100"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="planningCapacityResponse">
				<xsd:sequence>
					<xsd:element name="track" type="tns:capacity_key" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="capacity_key">
				<xsd:sequence>
					<xsd:element name="key" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="capacity" type="tns:capacity" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="capacity">
				<xsd:sequence>
					<xsd:element name="date" type="xsd:date" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="period" type="xsd:int" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="planningAllocateRequest">
				<xsd:sequence>
					<xsd:element name="workorder_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="segment" type="tns:capacity_key" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorderFileGetRequest">
				<xsd:sequence>
					<xsd:element name="file_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="sparepartGetRequest">
				<xsd:sequence>
					<xsd:element name="batch_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="sparepartGetResponse">
				<xsd:sequence>
					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="status" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="responsible" type="xsd:string" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="order" type="xsd:dateTime" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="delivery" type="xsd:date" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="note" type="xsd:string" maxOccurs="1" minOccurs="0"/>
					<xsd:element name="workorder" type="tns:workorder" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="sparepart" type="tns:sparepart" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="sparepartUpdateRequest">
				<xsd:sequence>
					<xsd:element name="batch_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="sparepart" type="tns:sparepart" maxOccurs="unbounded" minOccurs="0"/>
					<xsd:element name="supplier_note" maxOccurs="1" minOccurs="0">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:maxLength value="30"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="supplier_reference" maxOccurs="1" minOccurs="0">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:maxLength value="200"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="workorderExpenseRequest">
				<xsd:sequence>
					<xsd:element name="workorder_id" type="xsd:int" maxOccurs="1" minOccurs="1"/>
					<xsd:element name="lines" type="tns:invoice_line" maxOccurs="unbounded" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="workorderCreateRequest">
		<wsdl:part name="workorderCreateRequest" type="tns:workorderCreateRequest"/>
	</wsdl:message>
	<wsdl:message name="workorderCreateResponse">
		<wsdl:part name="workorderCreateResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="workorderListRequest">
		<wsdl:part name="workorderListRequest" type="tns:workorderListRequest"/>
	</wsdl:message>
	<wsdl:message name="workorderListResponse">
		<wsdl:part name="workorderListResponse" type="tns:workorderListResponse"/>
	</wsdl:message>
	<wsdl:message name="planningCapacityRequest">
		<wsdl:part name="planningCapacityRequest" type="tns:planningCapacityRequest"/>
	</wsdl:message>
	<wsdl:message name="planningCapacityResponse">
		<wsdl:part name="planningCapacityResponse" type="tns:planningCapacityResponse"/>
	</wsdl:message>
	<wsdl:message name="planningAllocateRequest">
		<wsdl:part name="planningAllocateRequest" type="tns:planningAllocateRequest"/>
	</wsdl:message>
	<wsdl:message name="planningAllocateResponse">
		<wsdl:part name="planningAllocateResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="invoiceListRequest">
		<wsdl:part name="invoiceListRequest" type="tns:empty"/>
	</wsdl:message>
	<wsdl:message name="invoiceListResponse">
		<wsdl:part name="invoiceListResponse" type="tns:invoiceListResponse"/>
	</wsdl:message>
	<wsdl:message name="invoiceGetRequest">
		<wsdl:part name="invoiceGetRequest" type="tns:invoiceGetRequest"/>
	</wsdl:message>
	<wsdl:message name="invoiceGetResponse">
		<wsdl:part name="invoiceGetResponse" type="tns:invoiceGetResponse"/>
	</wsdl:message>
	<wsdl:message name="invoiceDoneRequest">
		<wsdl:part name="invoiceDoneRequest" type="tns:invoiceDoneRequest"/>
	</wsdl:message>
	<wsdl:message name="invoiceDoneResponse">
		<wsdl:part name="invoiceDoneResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="invoiceAttachmentRequest">
		<wsdl:part name="invoiceAttachmentRequest" type="tns:invoiceAttachmentRequest"/>
	</wsdl:message>
	<wsdl:message name="invoiceAttachmentResponse">
		<wsdl:part name="invoiceAttachmentResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="paintmanagerRepairOrdersRequest">
		<wsdl:part name="paintmanagerRepairOrdersRequest" type="tns:empty"/>
	</wsdl:message>
	<wsdl:message name="paintmanagerRepairOrdersResponse">
		<wsdl:part name="paintmanagerRepairOrdersResponse" type="tns:paintmanagerRepairOrdersResponse"/>
	</wsdl:message>
	<wsdl:message name="paintmanagerMixesRequest">
		<wsdl:part name="paintmanagerMixesRequest" type="tns:paintmanagerMixesResponse"/>
	</wsdl:message>
	<wsdl:message name="paintmanagerMixesResponse">
		<wsdl:part name="paintmanagerMixesResponse" type="tns:empty"/>
	</wsdl:message>
	<wsdl:message name="jobproviderGetRequest">
		<wsdl:part name="jobproviderGetRequest" type="tns:jobproviderGetRequest"/>
	</wsdl:message>
	<wsdl:message name="jobproviderGetResponse">
		<wsdl:part name="jobproviderGetResponse" type="tns:jobprovider"/>
	</wsdl:message>
	<wsdl:message name="jobproviderUpdateRequest">
		<wsdl:part name="jobproviderUpdateRequest" type="tns:jobproviderUpdateRequest"/>
	</wsdl:message>
	<wsdl:message name="jobproviderUpdateResponse">
		<wsdl:part name="jobproviderUpdateResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="jobproviderListRequest">
		<wsdl:part name="jobproviderListRequest" type="tns:empty"/>
	</wsdl:message>
	<wsdl:message name="jobproviderListResponse">
		<wsdl:part name="jobproviderListResponse" type="tns:jobproviderListResponse"/>
	</wsdl:message>
	<wsdl:message name="principalListRequest">
		<wsdl:part name="principalListRequest" type="tns:principalListRequest"/>
	</wsdl:message>
	<wsdl:message name="principalListResponse">
		<wsdl:part name="principalListResponse" type="tns:principalListResponse"/>
	</wsdl:message>
	<wsdl:message name="principalGetRequest">
		<wsdl:part name="principalGetRequest" type="tns:principalGetRequest"/>
	</wsdl:message>
	<wsdl:message name="principalGetResponse">
		<wsdl:part name="principalGetResponse" type="tns:principal"/>
	</wsdl:message>
	<wsdl:message name="principalUpdateRequest">
		<wsdl:part name="principalUpdateRequest" type="tns:principalUpdateRequest"/>
	</wsdl:message>
	<wsdl:message name="principalUpdateResponse">
		<wsdl:part name="principalUpdateResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="brandListRequest">
		<wsdl:part name="brandListRequest" type="tns:empty"/>
	</wsdl:message>
	<wsdl:message name="brandListResponse">
		<wsdl:part name="brandListResponse" type="tns:brandListResponse"/>
	</wsdl:message>
	<wsdl:message name="workorderGetRequest">
		<wsdl:part name="workorderGetRequest" type="tns:workorderGetRequest"/>
	</wsdl:message>
	<wsdl:message name="workorderGetResponse">
		<wsdl:part name="workorderGetResponse" type="tns:workorder"/>
	</wsdl:message>
	<wsdl:message name="workorderActionRequest">
		<wsdl:part name="workorderActionRequest" type="tns:workorderActionRequest"/>
	</wsdl:message>
	<wsdl:message name="workorderActionResponse">
		<wsdl:part name="workorderActionResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="workorderFileGetRequest">
		<wsdl:part name="workorderFileGetRequest" type="tns:workorderFileGetRequest"/>
	</wsdl:message>
	<wsdl:message name="workorderFileGetResponse">
		<wsdl:part name="workorderFileGetResponse" type="tns:files"/>
	</wsdl:message>
	<wsdl:message name="bookingListRequest">
		<wsdl:part name="bookingListRequest" type="tns:bookingListRequest"/>
	</wsdl:message>
	<wsdl:message name="bookingListResponse">
		<wsdl:part name="bookingListResponse" type="tns:bookingListResponse"/>
	</wsdl:message>
	<wsdl:message name="bookingSetRequest">
		<wsdl:part name="bookingSetRequest" type="tns:bookingSetRequest"/>
	</wsdl:message>
	<wsdl:message name="bookingSetResponse">
		<wsdl:part name="bookingSetResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="sparepartGetRequest">
		<wsdl:part name="sparepartGetRequest" type="tns:sparepartGetRequest"/>
	</wsdl:message>
	<wsdl:message name="sparepartGetResponse">
		<wsdl:part name="sparepartGetResponse" type="tns:sparepartGetResponse"/>
	</wsdl:message>
	<wsdl:message name="sparepartUpdateRequest">
		<wsdl:part name="sparepartUpdateRequest" type="tns:sparepartUpdateRequest"/>
	</wsdl:message>
	<wsdl:message name="sparepartUpdateResponse">
		<wsdl:part name="sparepartUpdateResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="workorderExpenseRequest">
		<wsdl:part name="workorderExpenseRequest" type="tns:workorderExpenseRequest"/>
	</wsdl:message>
	<wsdl:message name="workorderExpenseResponse">
		<wsdl:part name="workorderExpenseResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:portType name="operations">
		<wsdl:operation name="workorderCreate">
			<wsdl:input message="tns:workorderCreateRequest"/>
			<wsdl:output message="tns:workorderCreateResponse"/>
		</wsdl:operation>
		<wsdl:operation name="workorderList">
			<wsdl:input message="tns:workorderListRequest"/>
			<wsdl:output message="tns:workorderListResponse"/>
		</wsdl:operation>
		<wsdl:operation name="workorderGet">
			<wsdl:input message="tns:workorderGetRequest"/>
			<wsdl:output message="tns:workorderGetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="workorderAction">
			<wsdl:input message="tns:workorderActionRequest"/>
			<wsdl:output message="tns:workorderActionResponse"/>
		</wsdl:operation>
		<wsdl:operation name="workorderFileGet">
			<wsdl:input message="tns:workorderFileGetRequest"/>
			<wsdl:output message="tns:workorderFileGetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="planningCapacity">
			<wsdl:input message="tns:planningCapacityRequest"/>
			<wsdl:output message="tns:planningCapacityResponse"/>
		</wsdl:operation>
		<wsdl:operation name="planningAllocate">
			<wsdl:input message="tns:planningAllocateRequest"/>
			<wsdl:output message="tns:planningAllocateResponse"/>
		</wsdl:operation>
		<wsdl:operation name="invoiceList">
			<wsdl:input message="tns:invoiceListRequest"/>
			<wsdl:output message="tns:invoiceListResponse"/>
		</wsdl:operation>
		<wsdl:operation name="invoiceGet">
			<wsdl:input message="tns:invoiceGetRequest"/>
			<wsdl:output message="tns:invoiceGetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="invoiceDone">
			<wsdl:input message="tns:invoiceDoneRequest"/>
			<wsdl:output message="tns:invoiceDoneResponse"/>
		</wsdl:operation>
		<wsdl:operation name="invoiceAttachment">
			<wsdl:input message="tns:invoiceAttachmentRequest"/>
			<wsdl:output message="tns:invoiceAttachmentResponse"/>
		</wsdl:operation>
		<wsdl:operation name="paintmanagerRepairOrders">
			<wsdl:input message="tns:paintmanagerRepairOrdersRequest"/>
			<wsdl:output message="tns:paintmanagerRepairOrdersResponse"/>
		</wsdl:operation>
		<wsdl:operation name="paintmanagerMixes">
			<wsdl:input message="tns:paintmanagerMixesRequest"/>
			<wsdl:output message="tns:paintmanagerMixesResponse"/>
		</wsdl:operation>
		<wsdl:operation name="jobproviderGet">
			<wsdl:input message="tns:jobproviderGetRequest"/>
			<wsdl:output message="tns:jobproviderGetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="jobproviderUpdate">
			<wsdl:input message="tns:jobproviderUpdateRequest"/>
			<wsdl:output message="tns:jobproviderUpdateResponse"/>
		</wsdl:operation>
		<wsdl:operation name="jobproviderList">
			<wsdl:input message="tns:jobproviderListRequest"/>
			<wsdl:output message="tns:jobproviderListResponse"/>
		</wsdl:operation>
		<wsdl:operation name="principalList">
			<wsdl:input message="tns:principalListRequest"/>
			<wsdl:output message="tns:principalListResponse"/>
		</wsdl:operation>
		<wsdl:operation name="principalGet">
			<wsdl:input message="tns:principalGetRequest"/>
			<wsdl:output message="tns:principalGetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="principalUpdate">
			<wsdl:input message="tns:principalUpdateRequest"/>
			<wsdl:output message="tns:principalUpdateResponse"/>
		</wsdl:operation>
		<wsdl:operation name="brandList">
			<wsdl:input message="tns:brandListRequest"/>
			<wsdl:output message="tns:brandListResponse"/>
		</wsdl:operation>
		<wsdl:operation name="bookingList">
			<wsdl:input message="tns:bookingListRequest"/>
			<wsdl:output message="tns:bookingListResponse"/>
		</wsdl:operation>
		<wsdl:operation name="bookingSet">
			<wsdl:input message="tns:bookingSetRequest"/>
			<wsdl:output message="tns:bookingSetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="sparepartGet">
			<wsdl:input message="tns:sparepartGetRequest"/>
			<wsdl:output message="tns:sparepartGetResponse"/>
		</wsdl:operation>
		<wsdl:operation name="sparepartUpdate">
			<wsdl:input message="tns:sparepartUpdateRequest"/>
			<wsdl:output message="tns:sparepartUpdateResponse"/>
		</wsdl:operation>
		<wsdl:operation name="workorderExpense">
			<wsdl:input message="tns:workorderExpenseRequest"/>
			<wsdl:output message="tns:workorderExpenseResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="standardbinding" type="tns:operations">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="workorderCreate">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/workorderCreate"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="workorderList">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/workorderList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="workorderGet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/workorderGet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="workorderAction">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/workorderAction"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="workorderFileGet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/workorderFileGet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="workorderExpense">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/workorderExpense"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="planningCapacity">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/planningCapacity"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="planningAllocate">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/planningAllocate"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="invoiceList">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/invoiceList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="invoiceGet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/invoiceGet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="invoiceDone">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/invoiceDone"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="invoiceAttachment">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/invoiceAttachment"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paintmanagerRepairOrders">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/paintmanagerRepairOrders"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paintmanagerMixes">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/paintmanagerMixes"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="jobproviderGet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/jobproviderGet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="jobproviderUpdate">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/jobproviderUpdate"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="jobproviderList">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/jobproviderList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="principalList">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/principalList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="principalGet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/principalGet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="principalUpdate">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/principalUpdate"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="brandList">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/brandList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="bookingList">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/bookingList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="bookingSet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/bookingSet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="sparepartGet">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/sparepartGet"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="sparepartUpdate">
			<soap:operation soapAction="https://www.ppg-processmanager.com/api/sparepartUpdate"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ProcessManagerAPI">
		<wsdl:port name="soapservice" binding="tns:standardbinding">
			<soap:address location="https://www.ppg-processmanager.com/api/v014/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
